Db_Server = "localhost"
Db_Port = 3306
Db_User = "root"
Db_Password = "root"
Db_Database = "Mukesh"
Db_Name = "mysql"
Db_Type = ""


SetMaxOpenConnsdb = "5"
SetMaxIdleConnsdb = "5"
SetConnMaxIdleTimedb = "10"